/**
 * Theme definitions for Code → Docs
 * Each theme defines colors for the code block background, text, and
 * a corresponding highlight.js stylesheet URL.
 */
const THEMES = {
    'github-light': {
        name: 'GitHub Light',
        hljsCss: 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/github.min.css',
        background: '#f6f8fa',
        textColor: '#24292e',
        borderColor: '#e1e4e8',
        lineNumberColor: '#6e7781',
        highlightLineColor: '#fff8c5',
        captionColor: '#24292e',
        // highlight.js token colors (GitHub Light theme)
        tokens: {
            'hljs-keyword':    { color: '#d73a49' },
            'hljs-built_in':   { color: '#005cc5' },
            'hljs-type':       { color: '#005cc5' },
            'hljs-literal':    { color: '#005cc5' },
            'hljs-number':     { color: '#005cc5' },
            'hljs-string':     { color: '#032f62' },
            'hljs-comment':    { color: '#6a737d', fontStyle: 'italic' },
            'hljs-doctag':     { color: '#d73a49' },
            'hljs-meta':       { color: '#005cc5' },
            'hljs-function':   { color: '#24292e' },
            'hljs-title':      { color: '#6f42c1' },
            'hljs-title.function_': { color: '#6f42c1' },
            'hljs-params':     { color: '#24292e' },
            'hljs-variable':   { color: '#e36209' },
            'hljs-attr':       { color: '#005cc5' },
            'hljs-attribute':  { color: '#032f62' },
            'hljs-symbol':     { color: '#005cc5' },
            'hljs-selector-tag':  { color: '#22863a' },
            'hljs-selector-class':{ color: '#6f42c1' },
            'hljs-selector-id':   { color: '#005cc5' },
            'hljs-name':       { color: '#22863a' },
            'hljs-tag':        { color: '#22863a' },
            'hljs-deletion':   { color: '#b31d28', backgroundColor: '#ffeef0' },
            'hljs-addition':   { color: '#22863a', backgroundColor: '#f0fff4' },
            'hljs-link':       { color: '#032f62' },
            'hljs-regexp':     { color: '#032f62' },
            'hljs-subst':      { color: '#24292e' },
            'hljs-property':   { color: '#005cc5' },
            'hljs-punctuation':{ color: '#24292e' },
            'hljs-operator':   { color: '#d73a49' },
        },
    },
    'github-dark': {
        name: 'GitHub Dark',
        hljsCss: 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/github-dark.min.css',
        background: '#0d1117',
        textColor: '#c9d1d9',
        borderColor: '#30363d',
        lineNumberColor: '#6e7681',
        highlightLineColor: '#3b2e00',
        captionColor: '#c9d1d9',
        tokens: {
            'hljs-keyword':    { color: '#ff7b72' },
            'hljs-built_in':   { color: '#79c0ff' },
            'hljs-type':       { color: '#79c0ff' },
            'hljs-literal':    { color: '#79c0ff' },
            'hljs-number':     { color: '#79c0ff' },
            'hljs-string':     { color: '#a5d6ff' },
            'hljs-comment':    { color: '#8b949e', fontStyle: 'italic' },
            'hljs-doctag':     { color: '#ff7b72' },
            'hljs-meta':       { color: '#79c0ff' },
            'hljs-function':   { color: '#c9d1d9' },
            'hljs-title':      { color: '#d2a8ff' },
            'hljs-title.function_': { color: '#d2a8ff' },
            'hljs-params':     { color: '#c9d1d9' },
            'hljs-variable':   { color: '#ffa657' },
            'hljs-attr':       { color: '#79c0ff' },
            'hljs-attribute':  { color: '#a5d6ff' },
            'hljs-symbol':     { color: '#79c0ff' },
            'hljs-selector-tag':  { color: '#7ee787' },
            'hljs-selector-class':{ color: '#d2a8ff' },
            'hljs-name':       { color: '#7ee787' },
            'hljs-tag':        { color: '#7ee787' },
            'hljs-deletion':   { color: '#ffdcd7', backgroundColor: '#67060c' },
            'hljs-addition':   { color: '#aff5b4', backgroundColor: '#033a16' },
            'hljs-link':       { color: '#a5d6ff' },
            'hljs-regexp':     { color: '#a5d6ff' },
            'hljs-subst':      { color: '#c9d1d9' },
            'hljs-property':   { color: '#79c0ff' },
            'hljs-punctuation':{ color: '#c9d1d9' },
            'hljs-operator':   { color: '#ff7b72' },
        },
    },
    'vs-light': {
        name: 'VS Code Light',
        hljsCss: 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/vs.min.css',
        background: '#ffffff',
        textColor: '#000000',
        borderColor: '#e0e0e0',
        lineNumberColor: '#237893',
        highlightLineColor: '#ffffcc',
        captionColor: '#000000',
        tokens: {
            'hljs-keyword':    { color: '#0000ff' },
            'hljs-built_in':   { color: '#267f99' },
            'hljs-type':       { color: '#267f99' },
            'hljs-literal':    { color: '#0000ff' },
            'hljs-number':     { color: '#098658' },
            'hljs-string':     { color: '#a31515' },
            'hljs-comment':    { color: '#008000', fontStyle: 'italic' },
            'hljs-doctag':     { color: '#0000ff' },
            'hljs-meta':       { color: '#267f99' },
            'hljs-function':   { color: '#000000' },
            'hljs-title':      { color: '#795e26' },
            'hljs-title.function_': { color: '#795e26' },
            'hljs-params':     { color: '#000000' },
            'hljs-variable':   { color: '#001080' },
            'hljs-attr':       { color: '#ff0000' },
            'hljs-attribute':  { color: '#a31515' },
            'hljs-symbol':     { color: '#0000ff' },
            'hljs-selector-tag':  { color: '#800000' },
            'hljs-selector-class':{ color: '#800000' },
            'hljs-name':       { color: '#800000' },
            'hljs-tag':        { color: '#800000' },
            'hljs-deletion':   { color: '#a31515' },
            'hljs-addition':   { color: '#098658' },
            'hljs-link':       { color: '#a31515' },
            'hljs-regexp':     { color: '#811f3f' },
            'hljs-subst':      { color: '#000000' },
            'hljs-property':   { color: '#001080' },
            'hljs-punctuation':{ color: '#000000' },
            'hljs-operator':   { color: '#000000' },
        },
    },
    'vs-dark': {
        name: 'VS Code Dark',
        hljsCss: 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/vs2015.min.css',
        background: '#1e1e1e',
        textColor: '#d4d4d4',
        borderColor: '#3c3c3c',
        lineNumberColor: '#858585',
        highlightLineColor: '#2a2d2e',
        captionColor: '#d4d4d4',
        tokens: {
            'hljs-keyword':    { color: '#569cd6' },
            'hljs-built_in':   { color: '#4ec9b0' },
            'hljs-type':       { color: '#4ec9b0' },
            'hljs-literal':    { color: '#569cd6' },
            'hljs-number':     { color: '#b5cea8' },
            'hljs-string':     { color: '#ce9178' },
            'hljs-comment':    { color: '#6a9955', fontStyle: 'italic' },
            'hljs-doctag':     { color: '#569cd6' },
            'hljs-meta':       { color: '#9cdcfe' },
            'hljs-function':   { color: '#d4d4d4' },
            'hljs-title':      { color: '#dcdcaa' },
            'hljs-title.function_': { color: '#dcdcaa' },
            'hljs-params':     { color: '#d4d4d4' },
            'hljs-variable':   { color: '#9cdcfe' },
            'hljs-attr':       { color: '#9cdcfe' },
            'hljs-attribute':  { color: '#ce9178' },
            'hljs-symbol':     { color: '#569cd6' },
            'hljs-selector-tag':  { color: '#d7ba7d' },
            'hljs-selector-class':{ color: '#d7ba7d' },
            'hljs-name':       { color: '#569cd6' },
            'hljs-tag':        { color: '#569cd6' },
            'hljs-deletion':   { color: '#ce9178' },
            'hljs-addition':   { color: '#b5cea8' },
            'hljs-link':       { color: '#ce9178' },
            'hljs-regexp':     { color: '#d16969' },
            'hljs-subst':      { color: '#d4d4d4' },
            'hljs-property':   { color: '#9cdcfe' },
            'hljs-punctuation':{ color: '#d4d4d4' },
            'hljs-operator':   { color: '#d4d4d4' },
        },
    },
    'monokai': {
        name: 'Monokai',
        hljsCss: 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/monokai.min.css',
        background: '#272822',
        textColor: '#f8f8f2',
        borderColor: '#49483e',
        lineNumberColor: '#8f908a',
        highlightLineColor: '#3e3d32',
        captionColor: '#f8f8f2',
        tokens: {
            'hljs-keyword':    { color: '#f92672' },
            'hljs-built_in':   { color: '#66d9ef', fontStyle: 'italic' },
            'hljs-type':       { color: '#66d9ef', fontStyle: 'italic' },
            'hljs-literal':    { color: '#ae81ff' },
            'hljs-number':     { color: '#ae81ff' },
            'hljs-string':     { color: '#e6db74' },
            'hljs-comment':    { color: '#75715e', fontStyle: 'italic' },
            'hljs-doctag':     { color: '#f92672' },
            'hljs-meta':       { color: '#66d9ef' },
            'hljs-function':   { color: '#f8f8f2' },
            'hljs-title':      { color: '#a6e22e' },
            'hljs-title.function_': { color: '#a6e22e' },
            'hljs-params':     { color: '#f8f8f2' },
            'hljs-variable':   { color: '#f8f8f2' },
            'hljs-attr':       { color: '#a6e22e' },
            'hljs-attribute':  { color: '#e6db74' },
            'hljs-symbol':     { color: '#ae81ff' },
            'hljs-selector-tag':  { color: '#f92672' },
            'hljs-selector-class':{ color: '#a6e22e' },
            'hljs-name':       { color: '#f92672' },
            'hljs-tag':        { color: '#f92672' },
            'hljs-deletion':   { color: '#f92672' },
            'hljs-addition':   { color: '#a6e22e' },
            'hljs-link':       { color: '#e6db74' },
            'hljs-regexp':     { color: '#e6db74' },
            'hljs-subst':      { color: '#f8f8f2' },
            'hljs-property':   { color: '#66d9ef' },
            'hljs-punctuation':{ color: '#f8f8f2' },
            'hljs-operator':   { color: '#f92672' },
        },
    },
};
